### ISSUE TITLE
Question : Table height

### ISSUE THREAD

**Issue by saki2fifty** [Badgerati/Pode.Web#189]

**Comment by saki2fifty** [comment]
Also, sorry...  When creating tables, I would like to adjust the height of rows to a smaller height than the default.  I can increase it, but can't figure out how to decrease it.  The purpose of this, is so that more data can fit on the page.

Thank you,

**Comment by Badgerati** [comment]
Hey @saki2fifty,

At the moment it's not possible with just the `New-PodeWebTable` function alone, but it can definitely be added!

To do it now, it should be possible to use a custom css file such as `/public/style.css` with content:

```css
table tr {
    height: 10px !important;
}
```

and use the css file via `Import-PodeWebStylesheet -Url /style.css`.

I also did see the original question 😄  I am going to look at making the sidebar work differently, so it can be more dynamic and render other components like pages.

**Comment by saki2fifty** [comment]
Yes, I removed that first question as I felt like a simpleton asking a simpleton question.  :)

With what we've used it for already, it would be great if we could add other types of content to the sidebar, as there is a lot of wasted space, at least in our case at the moment.

Thanks on the table tip, I'll try it after work!  So only add the css content you mentioned above to the .css file, import, and change my table args to target the .css with -CssClass 'xxx'?

Very much appreciated.

**Comment by Badgerati** [comment]
The `!important` on a css line tells the browser "use this rule and nothing else", overriding anything else set by Pode.Web, Bootstrap, or any other library.

For example:
```css
.table td {
    padding: 6px;
    border-bottom:1px;
    border-left:1px;
    font-size: 10px;
}
```

sometimes the `padding: 6px` might not apply, because a css rule in bootstrap has a higher priority; but if you do:
```css
.table td {
    padding: 6px !important;
    border-bottom:1px;
    border-left:1px;
    font-size: 10px;
}
```

then unless there's anything defined after you css file (which there shouldnt be, as custom files are loaded last), then the browser will ignore bootstraps and *should* use yours instead.

You can usually see what's going on by using F12/dev-console in the browser and inspecting an element. If your css rule has a line through it, then the browser is ignoring it :) 

If it won't go any smaller, then one of the following could also be affecting it: margin, line-height, height, min-height, or max-height
